version: '3.8'

services:
  app:
    image: todo-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-front-cont
    
  debug-helper:
    image: busybox