services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: ./Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app/
    ports:
      - 3001:3000
    container_name: todo-front-cont
  nginx:
      image: nginx:1.20.1
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 8080:80
      container_name: reverse-proxy
  server:
    image: todo-backend
    volumes:
      - ./todo-frontend/:/usr/src/app/
    ports:
      - 6000:3000
    environment:
      - REDIS_URL=//redis-todo:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo-todo:27017/the_database
    container_name: todo-backend
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
    container_name: mongo-todo
  redis:
    image: redis
    ports:
      - 2500:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
       - ./todo-backend/redis_data:/data
    container_name: redis-todo
volumes:
  mongo_data: